# Use Python as the base image
FROM python:3.12

# Set the working directory
WORKDIR /app

# Copy the source code
COPY . .

# Install dependencies
RUN pip install --default-timeout=1000 --retries 10 --no-cache-dir -r requirements.txt

# Expose the FastAPI port
EXPOSE 8000

# Run the FastAPI app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
